services:
  db:
    container_name: vdt_db
    image: postgres
    environment:
      POSTGRES_DB: vdt_db
      POSTGRES_USER: vdt_user
      POSTGRES_PASSWORD: vdt_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data